MVC_Project.WebBackend/Models/AllianceViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Project.WebBackend.Models
{
    public class AllianceFilterViewModel
    {
        [Display(Name = "Nombre")]
        public string Name { get; set; }

        [Display(Name = "Aliado")]
        public string AllyName { get; set; }
    }

    public class AlliancesListVM
    {
        public Int64 id { get; set; }
        public Guid uuid { get; set; }
        public string name { get; set; }
        public string allyName { get; set; }
        public decimal allyCommisionPercent { get; set; }
        public decimal customerDiscountPercent { get; set; }
        public string createdAt { get; set; }
        public string status { get; set; }
    }

    public class AllianceViewModel
    {
        public Int64 id { get; set; }
        public Guid uuid { get; set; }

        [Display(Name = "Nombre")]
        public string name { get; set; }

        [Display(Name = "Aliado")]
        public Int64 allyId { get; set; }
        public SelectList allyList { get; set; }

        [Display(Name = "% comisión aliado")]
        public decimal allyCommisionPercent { get; set; }

        [Display(Name = "% descuento cliente")]
        public decimal customerDiscountPercent { get; set; }

        [Display(Name = "Código promoción")]
        public string promotionCode { get; set; }

        [Display(Name = "Periodo a aplicar")]
        public bool applyPeriod { get; set; }

        [Display(Name = "Periodo inicial")]
        public int initialPeriod { get; set; }

        [Display(Name = "Periodo final")]
        public int finalPeriod { get; set; }

        [Display(Name = "% comisión aliado al finalizar")]
        public decimal finalAllyCommisionPercent { get; set; }

        [Display(Name = "Vigencia de alianza")]
        public bool allianceValidity { get; set; }

        [Display(Name = "Fecha Fin")]
        public DateTime finalDate { get; set; }

        public AllianceViewModel() {
            var list = new List<SelectListItem>();
            list.Add(new SelectListItem() { Text = "Seleccionar", Value = "-1" });

            allyList = new SelectList(list);
        }
    }

    public class AllyFilterViewModel
    {
        public Int64 Id { get; set; }

        [Display(Name = "Nombre")]
        public string Name { get; set; }
    }

    public class AlliesListVM
    {
        public Int64 id { get; set; }
        public Guid uuid { get; set; }
        public string name { get; set; }
        public string createdAt { get; set; }
        public string modifiedAt { get; set; }
        public string status { get; set; }
    }

    #region modelos para promociones
    public class PromotionFilterViewModel
    {
        [Display(Name = "Nombre")]
        public string Name { get; set; }

        [Display(Name = "Tipo")]
        public Int64 Type { get; set; }
        public SelectList typeList { get; set; }

        public PromotionFilterViewModel()
        {
            var list = new List<SelectListItem>();
            list.Add(new SelectListItem() { Text = "Todos", Value = "-1" });

            typeList = new SelectList(list);

        }
    }

    public class PromotionViewModel
    {
        public Int64 id { get; set; }
        public Guid uuid { get; set; }

        [Display(Name = "Nombre")]
        public string name { get; set; }

        [Display(Name = "Descuento en %")]
        public decimal discount { get; set; }

        [Display(Name = "Descuento en $")]
        public decimal discountRate { get; set; }

        [Display(Name = "Tipo")]
        public string TypeId { get; set; }
        public SelectList TypeList { get; set; }

        [Display(Name = "Clientes")]
        public Int64[] AccountId { get; set; }
        //public SelectList AccountList { get; set; }
        public MultiSelectList AccountMultipleList { get; set; }

        [Display(Name = "Periodo a aplicar")]
        public bool hasPeriod { get; set; }

        [Display(Name = "Periodo inicial")]
        public int initialPeriod { get; set; }

        [Display(Name = "Periodo final")]
        public int finalPeriod { get; set; }

        [Display(Name = "Vigencia de código")]
        public bool hasValidity { get; set; }

        [Display(Name = "Fecha Fin")]
        public DateTime finalDate { get; set; }

        //public DateTime validityInitialAt { get; set; }
        //public DateTime validityFinalAt { get; set; }

        public PromotionViewModel()
        {
            var list = new List<SelectListItem>();
            list.Add(new SelectListItem() { Text = "Seleccionar", Value = "-1" });
            TypeList = new SelectList(list);

        }
    }

    #endregion
}
 

MVC_Project.WebBackend/Controllers/AllianceController.cs
using LogHubSDK.Models;
using MVC_Project.Domain.Entities;
using MVC_Project.Domain.Model;
using MVC_Project.Domain.Services;
using MVC_Project.FlashMessages;
using MVC_Project.Utils;
using MVC_Project.WebBackend.AuthManagement;
using MVC_Project.WebBackend.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Project.WebBackend.Controllers
{
    public class AllianceController : Controller
    {
        private IAllyService _allyService;
        private IAllianceService _allianceService;

        #region Métodos para las alianzas
        public AllianceController(IAllyService allyService, IAllianceService allianceService)
        {
            _allyService = allyService;
            _allianceService = allianceService;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet, AllowAnonymous]
        public JsonResult GetAlliances(JQueryDataTableParams param, string filtros)
        {
            var userAuth = Authenticator.AuthenticatedUser;
            int totalDisplay = 0;
            int total = 0;
            var listResponse = new List<AllianceList>();
            var list = new List<AlliancesListVM>();
            string error = string.Empty;
            bool success = true;

            try
            {
                NameValueCollection filtersValues = HttpUtility.ParseQueryString(filtros);
                string Name = filtersValues.Get("Name");
                string AllyName = filtersValues.Get("AllyName");

                var pagination = new BasePagination();
                pagination.PageSize = param.iDisplayLength;
                pagination.PageNum = param.iDisplayLength == 1 ? (param.iDisplayStart + 1) : (int)(Math.Floor((decimal)((param.iDisplayStart + 1) / param.iDisplayLength)) + 1);

                listResponse = _allianceService.GetAlliancesList(pagination, Name, AllyName);

                //Corroborar los campos iTotalRecords y iTotalDisplayRecords
                if (listResponse.Count() > 0)
                {
                    totalDisplay = listResponse[0].Total;
                    total = listResponse.Count();

                    list = listResponse.Select(x => new AlliancesListVM
                    {
                        id = x.id,
                        uuid = x.uuid,
                        name = x.name,
                        allyName = x.allyName,
                        allyCommisionPercent = x.allyCommisionPercent,
                        customerDiscountPercent = x.customerDiscountPercent,
                        createdAt = x.createdAt.ToShortDateString(),
                        status = ((SystemStatus)Enum.Parse(typeof(SystemStatus), x.status)).GetDisplayName()
                    }).ToList();
                }
                
            }
            catch (Exception ex)
            {
                error = ex.Message.ToString();
                success = false;

                LogUtil.AddEntry(
                   "Se encontro un error: " + ex.Message.ToString(),
                   ENivelLog.Error,
                   userAuth.Id,
                   userAuth.Email,
                   EOperacionLog.ACCESS,
                   string.Format("Usuario {0} | Fecha {1}", userAuth.Email, DateUtil.GetDateTimeNow()),
                   ControllerContext.RouteData.Values["controller"].ToString() + "/" + Request.RequestContext.RouteData.Values["action"].ToString(),
                   string.Format("Usuario {0} | Fecha {1}", userAuth.Email, DateUtil.GetDateTimeNow())
                );
            }

            return Json(new
            {
                success = success,
                error = error,
                sEcho = param.sEcho,
                iTotalRecords = total,
                iTotalDisplayRecords = totalDisplay,
                aaData = list
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Delete(string uuid, FormCollection collection)
        {
            var userAuth = Authenticator.AuthenticatedUser;
            bool success = true;
            string error = String.Empty;
            try
            {
                var aliance = _allianceService.FindBy(x => x.uuid == Guid.Parse(uuid)).First();
                if (aliance != null)
                {
                    if (aliance.status == SystemStatus.ACTIVE.ToString())
                    {
                        aliance.status = SystemStatus.INACTIVE.ToString();
                    }
                    else
                    {
                        aliance.status = SystemStatus.ACTIVE.ToString();
                    }

                }
                _allianceService.Update(aliance);

                LogUtil.AddEntry(
                   "Actualización del status: " + aliance.name,
                   ENivelLog.Info,
                   userAuth.Id,
                   userAuth.Email,
                   EOperacionLog.ACCESS,
                   string.Format("Usuario {0} | Fecha {1}", userAuth.Email, DateUtil.GetDateTimeNow()),
                   ControllerContext.RouteData.Values["controller"].ToString() + "/" + Request.RequestContext.RouteData.Values["action"].ToString(),
                   "Estatus: " + aliance.status
                );

                //return Json(true, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                success = false;
                error = ex.Message.ToString();
                LogUtil.AddEntry(
                   "Se encontro un error: " + ex.Message.ToString(),
                   ENivelLog.Error,
                   userAuth.Id,
                   userAuth.Email,
                   EOperacionLog.ACCESS,
                   string.Format("Usuario {0} | Fecha {1}", userAuth.Email, DateUtil.GetDateTimeNow()),
                   ControllerContext.RouteData.Values["controller"].ToString() + "/" + Request.RequestContext.RouteData.Values["action"].ToString(),
                   string.Format("Usuario {0} | Fecha {1}", userAuth.Email, DateUtil.GetDateTimeNow())
                );
                //return Json(false, JsonRequestBehavior.AllowGet);
            }

            return Json(new
            {
                success = success,
                error = error
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Create()
        {
            ViewBag.Date = DateUtil.GetDateTimeNow().ToString("dd-MM-yyyy");

            AllianceViewModel model = new AllianceViewModel();
            try
            {
                var list = _allyService.GetAll();
                var allyList = list.Select(x => new SelectListItem() { Text = x.name, Value = x.id.ToString() }).ToList();
                model.allyList = new SelectList(allyList);
            }
            catch (Exception ex)
            {
                string error = ex.Message.ToString();
            }
            return View(model);
        }

        [Authorize, HttpPost, ValidateAntiForgeryToken, ValidateInput(true)]
        public ActionResult Create(AllianceViewModel model)
        {
            var authUser = Authenticator.AuthenticatedUser;
            try
            {
                if (!ModelState.IsValid)
                    throw new Exception("El modelo de entrada no es válido");

                if (_allianceService.FindBy(x => x.name == model.name).Any())
                    throw new Exception("Ya existe una alianza con el Nombre proporcionado");

                DateTime todayDate = DateUtil.GetDateTimeNow();

                Alliance alliance = new Alliance()
                {
                    uuid = Guid.NewGuid(),
                    name = model.name,
                    allyCommisionPercent = model.allyCommisionPercent,
                    customerDiscountPercent = model.customerDiscountPercent,
                    promotionCode = model.promotionCode,
                    allianceValidity = model.allianceValidity,
                    applyPeriod = model.applyPeriod,
                    createdAt = todayDate,
                    modifiedAt = todayDate,
                    status = SystemStatus.ACTIVE.ToString(),
                    ally = new Ally { id = model.allyId }
                };

                var ally = _allyService.FirstOrDefault(x => x.id == model.allyId);

                if (ally != null)
                {
                    var arrayS = model.promotionCode.Split('-');
                    var numCons = ally.consecutive + 1;
                    ally.consecutive = numCons;
                    ally.modifiedAt = todayDate;

                    if (arrayS.Count() != 3 || arrayS[2] != numCons.ToString())
                    {
                        arrayS[2] = numCons.ToString();
                        model.promotionCode = string.Join("-", arrayS);
                        ally.consecutive = numCons;
                    }
                }


                if (model.applyPeriod)
                {
                    alliance.initialPeriod = model.initialPeriod;
                    alliance.finalPeriod = model.finalPeriod;
                    alliance.finalAllyCommisionPercent = model.finalAllyCommisionPercent;
                }

                if (model.allianceValidity)
                {
                    alliance.finalDate = model.finalDate;
                    alliance.initialDate = model.finalDate;
                }

                _allianceService.CreateAlliance(alliance, ally);

                LogUtil.AddEntry(
                   "Alianza creada: " + alliance.name,
                   ENivelLog.Info,
                   authUser.Id,
                   authUser.Email,
                   EOperacionLog.ACCESS,
                   string.Format("Usuario {0} | Fecha {1}", authUser.Email, DateUtil.GetDateTimeNow()),

MVC_Project.WebBackend/Views/Alliance/Allies.cshtml
@model MVC_Project.WebBackend.Models.AllyFilterViewModel
@using MVC_Project.WebBackend.AuthManagement
@using MVC_Project.WebBackend.AuthManagement.Models
@{
    ViewBag.Title = "Aliados";

    var controllerName = HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString();
    AuthUser user = (AuthUser)Authenticator.AuthenticatedUser;
    var hasFullAccessController = user.HasFullAccessController(controllerName);
}

@section styles {
    @*
        @Styles.Render("~/plugins/dataTablesStyles")*@    
    <style>
        .hide {
            display: none;
        }
    </style>
}

<div class="wrapper wrapper-content animated fadeInRight">

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                @using (Html.BeginForm("GetAllies", "Alliance", FormMethod.Post, new { @id = "SearchForm" }))
                {
                    <div class="ibox-title">
                        <h5>Búsqueda</h5>
                    </div>
                    <div class="ibox-content clearfix">
                        <div class="row">
                            <div class="col-12 col-sm-4">
                                <div class="form-group">
                                    @Html.LabelFor(m => m.Name, new { @class = "" })
                                    @Html.TextBoxFor(m => m.Name, new { @Class = "form-control form-control-sm txtFiltro", filtro = "true", filtro_order = "1", @maxlength = "100", @autocomplete = "off" })
                                </div>
                            </div>
                            <div class="col-12 offset-8 col-sm-4 col-lg-4">
                                <br />
                                <button type="button" class="btn btn-sm btn-color btn-filter-rol"><i class="fas fa-search"></i> Buscar</button>
                                &nbsp;
                                <button type="button" id="btnClearForm" class="btn btn-sm btn-default"><i class="fas fa-eraser "></i> Limpiar</button>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Resultado</h5>
                    @if (hasFullAccessController)
                    {
                        <div class="ibox-tools">
                            <a href="@Url.Action("CreateAlly", "Alliance")" class="btn btn-sm btn-color btn-d0"><span class="fas fa-plus-square"></span> Crear Aliado</a>
                        </div>
                    }
                </div>
                <div class="ibox-content">
                    <div class="table-responsive">
                        <table id="table" class="table table-striped table-bordered"></table>
                    </div>
                </div>
            </div>
        </div>
    </div>   
</div>
@section scripts{
    @Scripts.Render("~/custom/Utils")
    @Scripts.Render("~/plugins/dataTables")

    <script>
        $(function () {
            var customer = new CustomerIndexControlador('table',
                '@Url.Action("GetCustomers")',
                '@Url.Action("Edit")',
                '@Url.Action("ExportListCustomer")',
                '@Url.Action("CustomerUpload")',
                '@Url.Action("ExportTemplate")',
                '@hasFullAccessController' == 'True'
            );
            customer.init();
        });
    </script>

    @Scripts.Render("~/views/customerIndex")
}

MVC_Project.WebBackend/Views/Alliance/AllyCreate.cshtml
@model MVC_Project.WebBackend.Models.AllyFilterViewModel
@using MVC_Project.Utils

@{
    /**/

    ViewBag.Title = "Nuevo Aliado";
}

@section styles{
    <style>
        .hidden {
            display: none;
        }
    </style>
}


<div class="wrapper wrapper-content animated fadeInRight">
    <div class="">
        @using (Html.BeginForm("AllyCreate", "Alliance", FormMethod.Post, new { role = "form", @id = "CreateForm", @class = "row" }))
        {
            <div class="col-lg-12">
                @Html.AntiForgeryToken()

                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Datos del Aliado</h5>
                    </div>
                    <div class="ibox-content">
                        <div class="form-horizontal">
                            <div class="form-group row">
                                @Html.LabelFor(m => m.Name, new { @class = "col-form-label col-12 col-md-2 control-label" })

                                <div class="col-12 col-md-8">
                                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control required", @maxlength = "50" })
                                </div>
                            </div>
                            <div class="form-group row pull-right">
                                <div class="col-md-8 offset-2 text-right">
                                    <a href='@Url.Action("AllyIndex", "Alliance")' class='btn btn-white'><i class="fa fa-times"></i> Cancelar</a>
                                    <button type="button" onclick="validarDatos()" class="btn btn-color"> <i class="fa fa-save"></i> Guardar </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/plugins/validate")
    @Scripts.Render("~/plugins/toastr")

    <script>
        function validarDatos() {
            if (!$('#CreateForm').valid()) {
                return;
            }
            $('#CreateForm').submit();
        }

        $.validator.addMethod("Alphanumeric",
            function (value, element) {
                return value.match(/^[A-Za-zÀ-ÿ\u00f1\u00d10-9 _.-]+$|^$/);
            }, "El campo debe ser alfanumérico"
        );
        $("#CreateForm").validate({
            rules: {
                Name: {
                    Alphanumeric: true
                }
            }
        });
    </script>
}

MVC_Project.WebBackend/Views/Alliance/AllyEdit.cshtml
@model MVC_Project.WebBackend.Models.AllyFilterViewModel
@using MVC_Project.Utils

@{
    ViewBag.Title = "Editar Aliado";
}

@section styles{
    <style>
        .hidden {
            display: none;
        }
    </style>
}

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="">
        @using (Html.BeginForm("AllyEdit", "Alliance", FormMethod.Post, new { role = "form", @id = "CreateForm", @class = "row" }))
        {
            <div class="col-lg-12">
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Datos del Aliado</h5>
                    </div>
                    <div class="ibox-content">
                        <div class="form-horizontal">
                            <input name="Id" type="hidden" value="@Model.Id" />
                            <div class="form-group row">
                                @Html.LabelFor(m => m.Name, new { @class = "col-form-label col-12 col-md-2 control-label" })
                                <div class="col-12 col-md-8">
                                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control required", @maxlength = "50" })
                                </div>
                            </div>
                            <div class="form-group row pull-right">
                                <div class="col-md-8 offset-2 text-right">
                                    <a href='@Url.Action("AllyIndex", "Alliance")' class='btn btn-white'><i class="fa fa-times"></i> Cancelar</a>
                                    <button onclick="validarDatos()" type="button" class="btn btn-color"> <i class="fa fa-save"></i> Guardar </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/plugins/validate")
    @Scripts.Render("~/plugins/toastr")

    <script>
        function validarDatos() {
            if (!$('#CreateForm').valid()) {
                return;
            }
            $('#CreateForm').submit();
        }
        $.validator.addMethod("Alphanumeric",
            function (value, element) {
                return value.match(/^[A-Za-zÀ-ÿ\u00f1\u00d10-9 _.-]+$|^$/);
            }, "El campo debe ser alfanumérico"
        );
        $("#CreateForm").validate({
            rules: {
                Name: {
                    Alphanumeric: true
                }
            }
        });
    </script>
}

MVC_Project.WebBackend/Views/Alliance/AllyIndex.cshtml
@model MVC_Project.WebBackend.Models.AllyFilterViewModel
@using MVC_Project.WebBackend.AuthManagement
@using MVC_Project.WebBackend.AuthManagement.Models
@{
    ViewBag.Title = "Aliados";

    var controllerName = HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString();
    AuthUser user = (AuthUser)Authenticator.AuthenticatedUser;
    var hasFullAccessController = user.HasFullAccessController(controllerName);
}

@section styles {
    @*
        @Styles.Render("~/plugins/dataTablesStyles")*@    
    <style>
        .hide {
            display: none;
        }
    </style>
}

<div class="wrapper wrapper-content animated fadeInRight">

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                @using (Html.BeginForm("GetAllies", "Alliance", FormMethod.Post, new { @id = "SearchForm" }))
                {
                    <div class="ibox-title">
                        <h5>Búsqueda</h5>
                    </div>
                    <div class="ibox-content clearfix">
                        <div class="row">
                            <div class="col-12 col-sm-4">
                                <div class="form-group">
                                    @Html.LabelFor(m => m.Name, new { @class = "" })
                                    @Html.TextBoxFor(m => m.Name, new { @Class = "form-control form-control-sm txtFiltro", filtro = "true", filtro_order = "1", @maxlength = "100", @autocomplete = "off" })
                                </div>
                            </div>
                            <div class="col-12 offset-4 col-sm-4 col-lg-4">
                                <br />
                                <button type="button" class="btn btn-sm btn-color btn-filter-rol"><i class="fas fa-search"></i> Buscar</button>
                                &nbsp;
                                <button type="button" id="btnClearForm" class="btn btn-sm btn-default"><i class="fas fa-eraser "></i> Limpiar</button>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Resultado</h5>
                    @if (hasFullAccessController)
                    {
                        <div class="ibox-tools">
                            <a href="@Url.Action("AllyCreate", "Alliance")" class="btn btn-sm btn-color btn-d0"><span class="fas fa-plus-square"></span> Crear Aliado</a>
                        </div>
                    }
                </div>
                <div class="ibox-content">
                    <div class="table-responsive">
                        <table id="table" class="table table-striped table-bordered"></table>
                    </div>
                </div>
            </div>
        </div>
    </div>   
</div>
@section scripts{
    @Scripts.Render("~/custom/Utils")
    @Scripts.Render("~/plugins/dataTables")

    <script>
        $(function () {
            var ally = new AllyIndexControlador('table',
                '@Url.Action("GetAllies")',
                '@Url.Action("AllyEdit")',               
                '@hasFullAccessController' == 'True'
            );
            ally.init();
        });
    </script>

    @Scripts.Render("~/views/allyIndex")
}

MVC_Project.WebBackend/Views/Alliance/Index.cshtml
@model MVC_Project.WebBackend.Models.AllianceFilterViewModel
@using MVC_Project.WebBackend.AuthManagement
@using MVC_Project.WebBackend.AuthManagement.Models
@{
    ViewBag.Title = "Alianzas";

    var controllerName = HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString();
    AuthUser user = (AuthUser)Authenticator.AuthenticatedUser;
    var hasFullAccessController = user.HasFullAccessController(controllerName);
}

@section styles {
    @*
        @Styles.Render("~/plugins/dataTablesStyles")*@
    <style>
        .hide {
            display: none;
        }
    </style>
}

<div class="wrapper wrapper-content animated fadeInRight">

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                @using (Html.BeginForm("GetAlliances", "Alliance", FormMethod.Post, new { @id = "SearchForm" }))
                {
                    <div class="ibox-title">
                        <h5>Búsqueda</h5>
                    </div>
                    <div class="ibox-content clearfix">
                        <div class="row">
                            <div class="col-12 col-sm-4">
                                <div class="form-group">
                                    @Html.LabelFor(m => m.Name, new { @class = "" })
                                    @Html.TextBoxFor(m => m.Name, new { @Class = "form-control form-control-sm txtFiltro", filtro = "true", filtro_order = "1", @maxlength = "100", @autocomplete = "off" })
                                </div>
                            </div>
                            <div class="col-12 col-sm-4">
                                <div class="form-group">
                                    @Html.LabelFor(m => m.AllyName, new { @class = "" })
                                    @Html.TextBoxFor(m => m.AllyName, new { @Class = "form-control form-control-sm txtFiltro", filtro = "true", filtro_order = "1", @maxlength = "100", @autocomplete = "off" })
                                </div>
                            </div>
                            <div class="col-12 col-sm-4 col-lg-4">
                                <br />
                                <button type="button" class="btn btn-sm btn-color btn-filter-rol"><i class="fas fa-search"></i> Buscar</button>
                                &nbsp;
                                <button type="button" id="btnClearForm" class="btn btn-sm btn-default"><i class="fas fa-eraser "></i> Limpiar</button>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Resultado</h5>
                    @if (hasFullAccessController)
                    {
                        <div class="ibox-tools">
                            <a href="@Url.Action("Create", "Alliance")" class="btn btn-sm btn-color btn-d0"><span class="fas fa-plus-square"></span> Crear Alianza</a>
                        </div>
                    }
                </div>
                <div class="ibox-content">
                    <div class="table-responsive">
                        <table id="table" class="table table-striped table-bordered"></table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts{
    @Scripts.Render("~/custom/Utils")
    @Scripts.Render("~/plugins/dataTables")

    <script>
        $(function () {
            var alliance = new AllianceIndexControlador('table',
                '@Url.Action("GetAlliances")',
                '@Url.Action("Edit")',
                '@Url.Action("Delete")',
                '@hasFullAccessController' == 'True'
            );
            alliance.init();            
        });
    </script>

    @Scripts.Render("~/views/allianceIndex")
}