MVC_Project.WebBackend/Models/ProviderViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Project.WebBackend.Models
{
    public class ProviderFilterViewModel
    {
        public int Id { get; set; }

        [Display(Name = "RFC")]
        public string RFC { get; set; }

        [Display(Name = "Nombre/Razón Social")]
        public string BusinessName { get; set; }

        [Display(Name = "Email")]
        public string Email { get; set; }
     
        [Display(Name = "Teléfono")]
        public string Phone { get; set; }
    }

    public class ProviderViewModel
    {
        public Int64 Id { get; set; }

        //[Required]
        [Display(Name = "Nombre(s)")]
        public string FistName { get; set; }

        //[Required]
        [Display(Name = "Apellido(s)")]
        public string LastName { get; set; }

        //[Required]
        [Display(Name = "RFC")]
        public string RFC { get; set; }

        [Display(Name = "CURP")]
        public string CURP { get; set; }

        [Display(Name = "Razón Social")]
        public string BusinessName { get; set; }

        [Display(Name = "Tipo Régimen Fiscal")]
        public string taxRegime { get; set; }
        public List<SelectListItem> ListRegimen { get; set; }

        [Display(Name = "Calle y Cruzamientos")]
        public string Street { get; set; }

        [Display(Name = "Número Exterior")]
        public string OutdoorNumber { get; set; }

        [Display(Name = "Número Interior")]
        public string InteriorNumber { get; set; }

        [Display(Name = "Colonia")]
        public Int64? Colony { get; set; }
        public List<SelectListItem> ListColony { get; set; }

        //[Required]
        [Display(Name = "C.P.")]
        public string ZipCode { get; set; }

        [Display(Name = "Alcaldía/Municipio")]
        public Int64? Municipality { get; set; }
        public List<SelectListItem> ListMunicipality { get; set; }

        [Display(Name = "Estado")]
        public Int64? State { get; set; }
        public List<SelectListItem> ListState { get; set; }

        [Display(Name = "País")]
        public Int64? Country { get; set; }
        public List<SelectListItem> ListCountry { get; set; }
        
        public bool DeliveryAddress { get; set; }

        public List<ProviderContactsViewModel> Emails { get; set; }
        public List<ProviderContactsViewModel> Phones { get; set; }
        public string dataContacts { get; set; }
        public string indexPhone { get; set; }
        public string indexEmail { get; set; }

        public ProviderViewModel()
        {
            ListColony = new List<SelectListItem>();
            ListState = new List<SelectListItem>();
            ListCountry = new List<SelectListItem>();
            ListMunicipality = new List<SelectListItem>();
            ListRegimen = new List<SelectListItem>();
            Emails = new List<ProviderContactsViewModel>();
            Phones = new List<ProviderContactsViewModel>();
        }
    }

    public class ProviderContactsViewModel
    {
        public Int64 Id { get; set; }
        public string TypeContact { get; set; }
        public string EmailOrPhone { get; set; }
    }

    public class InvoicesReceivedListVM
    {
        public Int64 id { get; set; }
        //public Guid uuid { get; set; }
        public string folio { get; set; }
        public string serie { get; set; }
        public string paymentMethod { get; set; }
        public string paymentForm { get; set; }
        public string currency { get; set; }
        public string amount { get; set; }
        public string iva { get; set; }
        public string totalAmount { get; set; }
        public string invoicedAt { get; set; }
        public string rfc { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string paymentFormDescription { get; set; }
        public string businessName { get; set; }
        public string type { get; set; }
        public bool hasXML { get; set; }
    }

    public class DataCFDI
    {

    }
}

MVC_Project.WebBackend/Controllers/ProviderController.cs
using ExcelDataReader;
using LogHubSDK.Models;
using MVC_Project.BackendWeb.Attributes;
using MVC_Project.Domain.Entities;
using MVC_Project.Domain.Model;
using MVC_Project.Domain.Services;
using MVC_Project.FlashMessages;
using MVC_Project.Integrations.Storage;
using MVC_Project.Utils;
using MVC_Project.WebBackend.AuthManagement;
using MVC_Project.WebBackend.Models;
using Newtonsoft.Json;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Configuration;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml;

namespace MVC_Project.WebBackend.Controllers
{
    public class ProviderController : Controller
    {
        private IAccountService _accountService;
        private IProviderService _providerService;
        private IStateService _stateService;
        private ICurrencyService _currencyService;
        private IPaymentFormService _paymentFormService;
        private IPaymentMethodService _paymentMethodService;
        private IInvoiceReceivedService _invoiceReceivedService;
        private ICountryService _countryService;

        public ProviderController(IAccountService accountService, IProviderService providerService, IStateService stateService,
            ICurrencyService currencyService, IPaymentFormService paymentFormService, IPaymentMethodService paymentMethodService,
            IInvoiceReceivedService invoiceReceivedService, ICountryService countryService)
        {
            _accountService = accountService;
            _providerService = providerService;
            _stateService = stateService;
            _currencyService = currencyService;
            _paymentFormService = paymentFormService;
            _paymentMethodService = paymentMethodService;
            _invoiceReceivedService = invoiceReceivedService;
            _countryService = countryService;
        }

        // GET: Provider
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult Create()
        {
            var userAuth = Authenticator.AuthenticatedUser;
            try
            {
                var createProvider = new ProviderViewModel();

                SetCombos(string.Empty, ref createProvider);

                return View(createProvider);
            }
            catch (Exception ex)
            {
                MensajeFlashHandler.RegistrarMensaje(ex.Message.ToString(), TiposMensaje.Error);
                LogUtil.AddEntry(
                  "Se encontro un error: " + ex.Message.ToString(),
                  ENivelLog.Error,
                  userAuth.Id,
                  userAuth.Email,
                  EOperacionLog.ACCESS,
                  string.Format("Usuario {0} | Fecha {1}", userAuth.Email, DateUtil.GetDateTimeNow()),
                  ControllerContext.RouteData.Values["controller"].ToString() + "/" + Request.RequestContext.RouteData.Values["action"].ToString(),
                  string.Format("Usuario {0} | Fecha {1}", userAuth.Email, DateUtil.GetDateTimeNow())
               );
                return RedirectToAction("Index");
            }
            // return View();
        }

        [Authorize, HttpPost, ValidateAntiForgeryToken, ValidateInput(true)]
        public ActionResult Create(ProviderViewModel model)
        {
            var authUser = Authenticator.AuthenticatedUser;
            try
            {
                if (!ModelState.IsValid)
                    throw new Exception("El registro de proveedor no es válido");


                if (_providerService.FindBy(x => x.rfc == model.RFC && x.account.id == authUser.Account.Id).Any())
                    throw new Exception("Ya existe un Proveedor con el RFC proporcionado");

                //Account account = _accountService.FindBy(x => x.id == authUser.Account.Id).FirstOrDefault();
                DateTime todayDate = DateUtil.GetDateTimeNow();

                Provider provider = new Provider()
                {
                    uuid = Guid.NewGuid(),
                    account = new Account { id = authUser.Account.Id },
                    firstName = model.FistName,
                    lastName = model.LastName,
                    rfc = model.RFC,
                    curp = model.CURP,
                    businessName = model.BusinessName,
                    taxRegime = model.taxRegime,
                    street = model.Street,
                    interiorNumber = model.InteriorNumber,
                    outdoorNumber = model.OutdoorNumber,
                    zipCode = model.ZipCode,
                    deliveryAddress = model.DeliveryAddress,
                    createdAt = todayDate,
                    modifiedAt = todayDate,
                    status = SystemStatus.ACTIVE.ToString(),
                };

                if (model.taxRegime == TypeTaxRegimen.PERSONA_FISICA.ToString())
                    provider.businessName = model.BusinessName;

                if (model.Colony.Value > 0)
                    provider.colony = model.Colony.Value;
                if (model.Municipality.Value > 0)
                    provider.municipality = model.Municipality.Value;
                if (model.State.Value > 0)
                    provider.state = model.State.Value;
                if (model.Country.Value > 0)
                    provider.country = model.Country.Value;

                List<string> indexsP = new List<string>();
                List<string> indexsE = new List<string>();

                if (model.indexPhone != null)
                    indexsP = model.indexPhone.Split(',').ToList();

                if (model.indexEmail != null)
                    indexsE = model.indexEmail.Split(',').ToList();

                if (model.Emails.Count() > 0)
                {
                    for (int i = 0; i < model.Emails.Count(); i++)
                    {
                        if (model.Phones[i].EmailOrPhone != null && model.Emails[i].EmailOrPhone.Trim() != "" && !indexsE.Contains(i.ToString()))
                        {
                            ProviderContact email = new ProviderContact()
                            {
                                emailOrPhone = model.Emails[i].EmailOrPhone,
                                typeContact = model.Emails[i].TypeContact,
                                provider = provider,
                                createdAt = todayDate,
                                modifiedAt = todayDate,
                                status = SystemStatus.ACTIVE.ToString()
                            };

                            provider.providerContacts.Add(email);
                        }
                    }
                }

                if (model.Phones.Count() > 0)
                {
                    for (int i = 0; i < model.Phones.Count(); i++)
                    {
                        if (model.Phones[i].EmailOrPhone != null && model.Phones[i].EmailOrPhone.Trim() != "" && !indexsP.Contains(i.ToString()))
                        {
                            ProviderContact phone = new ProviderContact()
                            {
                                emailOrPhone = model.Phones[i].EmailOrPhone,
                                typeContact = model.Phones[i].TypeContact,
                                provider = provider,
                                createdAt = todayDate,
                                modifiedAt = todayDate,
                                status = SystemStatus.ACTIVE.ToString()
                            };

                            provider.providerContacts.Add(phone);
                        }
                    }
                }

                _providerService.Create(provider);
                LogUtil.AddEntry(
                    "Nuevo proveedor creado: " + provider.businessName,
                    ENivelLog.Info,
                    authUser.Id,
                    authUser.Email,
                    EOperacionLog.ACCESS,
                    string.Format("Usuario {0} | Fecha {1}", authUser.Email, DateUtil.GetDateTimeNow()),
                    ControllerContext.RouteData.Values["controller"].ToString() + "/" + Request.RequestContext.RouteData.Values["action"].ToString(),
                    JsonConvert.SerializeObject(provider)
                );
                MensajeFlashHandler.RegistrarMensaje("Registro exitoso", TiposMensaje.Success);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                MensajeFlashHandler.RegistrarMensaje(ex.Message.ToString(), TiposMensaje.Error);

                SetCombos(model.ZipCode, ref model);

                LogUtil.AddEntry(
                   "Se encontro un error: " + ex.Message.ToString(),
                   ENivelLog.Error,
                   authUser.Id,
                   authUser.Email,
                   EOperacionLog.ACCESS,
                   string.Format("Usuario {0} | Fecha {1}", authUser.Email, DateUtil.GetDateTimeNow()),
                   ControllerContext.RouteData.Values["controller"].ToString() + "/" + Request.RequestContext.RouteData.Values["action"].ToString(),
                   string.Format("Usuario {0} | Fecha {1}", authUser.Email, DateUtil.GetDateTimeNow())
                );

                return View(model);
            }
        }

        public ActionResult Edit(string uuid)
        {
            var userAuth = Authenticator.AuthenticatedUser;
            try
            {
                ProviderViewModel model = new ProviderViewModel();


                var provider = _providerService.FirstOrDefault(x => x.uuid == Guid.Parse(uuid) && x.account.id == userAuth.Account.Id);
                if (provider == null)

MVC_Project.WebBackend/Views/Provider/Create.cshtml
@model MVC_Project.WebBackend.Models.ProviderViewModel
@using MVC_Project.Utils

@{
    /**/


    ViewBag.Title = "Nuevo Proveedor";
}

@section styles{
    <link href="~/Content/template/plugins/jasny/jasny-bootstrap.min.css" rel="stylesheet" />
    <style>
        .heightLabel {
            height: 55px;
        }

        .hidden {
            display: none;
        }
    </style>
    <link href="~/Content/template/plugins/iCheck/skins/square/blue.css" rel="stylesheet" />
}


<div class="wrapper wrapper-content content-padding animated fadeInRight">
    <div class="box-degradient">
        @using (Html.BeginForm("Create", "Provider", FormMethod.Post, new { role = "form", @id = "CreateForm", @class = "row" }))
        {
            <div class="col-lg-12">
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Datos del Proveedor</h5>
                    </div>
                    <div class="ibox-content">
                        <div class="form-horizontal">
                            <div class="form-group row">
                                <div class="col-12 col-md-4">
                                    @*@Html.LabelFor(m => m.RFC, new { @class = "col-form-label control-label" })*@
                                    @Html.TextBoxFor(m => m.RFC, new { @class = "form-control input-text", @maxlength = "13", placeholder = HttpUtility.HtmlDecode(Html.DisplayNameFor(x => x.RFC).ToHtmlString()) })
                                </div>
                                <div class="col-12 col-md-4">
                                    @*@Html.LabelFor(m => m.FistName, new { @class = "col-form-label control-label FistName" })*@
                                    @Html.TextBoxFor(m => m.FistName, new { @class = "form-control input-text", @maxlength = "50", placeholder = HttpUtility.HtmlDecode(Html.DisplayNameFor(x => x.FistName).ToHtmlString()) })
                                </div>
                                <div class="col-12 col-md-4">
                                    @*@Html.LabelFor(m => m.LastName, new { @class = "col-form-label control-label LastName" })*@
                                    @Html.TextBoxFor(m => m.LastName, new { @class = "form-control input-text", @maxlength = "50", placeholder = HttpUtility.HtmlDecode(Html.DisplayNameFor(x => x.LastName).ToHtmlString()) })
                                </div>
                            </div>
                            <div class="form-group row">
                                @*<div class="col-12 col-md-4">
                                        @Html.LabelFor(m => m.CURP, new { @class = "col-form-label control-label" })
                                        @Html.TextBoxFor(m => m.CURP, new { @class = "form-control" })
                                    </div>*@
                                <div class="col-12 col-md-8 businessName hidden">
                                    @*@Html.LabelFor(m => m.BusinessName, new { @class = "col-form-label control-label" })*@
                                    @Html.TextBoxFor(m => m.BusinessName, new { @class = "form-control input-text", @maxlength = "250", placeholder = HttpUtility.HtmlDecode(Html.DisplayNameFor(x => x.BusinessName).ToHtmlString()) })
                                </div>
                                <div class="col-12 col-md-4">
                                    @Html.LabelFor(m => m.taxRegime, new { @class = "col-form-label control-label" })
                                    @*@Html.TextBoxFor(m => m.taxRegime, new { @class = "form-control" })*@
                                    @Html.DropDownListFor(m => m.taxRegime, Model.ListRegimen, new { @class = "chosen-select" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Domicilio de Ubicación (Domicilio Fiscal)</h5>
                    </div>
                    <div class="ibox-content">
                        <div class="form-horizontal">
                            <div class="form-group row">
                                <div class="col-12 col-md-8">
                                    @*@Html.LabelFor(m => m.Street, new { @class = "col-form-label control-label" })*@
                                    @Html.TextBoxFor(m => m.Street, new { @class = "form-control input-text", @maxlength = "250", placeholder = HttpUtility.HtmlDecode(Html.DisplayNameFor(x => x.Street).ToHtmlString()) })
                                </div>
                                <div class="col-12 col-md-4">
                                    @*@Html.LabelFor(m => m.OutdoorNumber, new { @class = "col-form-label control-label" })*@
                                    @Html.TextBoxFor(m => m.OutdoorNumber, new { @class = "form-control input-text", @maxlength = "100", placeholder = HttpUtility.HtmlDecode(Html.DisplayNameFor(x => x.OutdoorNumber).ToHtmlString()) })
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-12 col-md-4">
                                    @*@Html.LabelFor(m => m.InteriorNumber, new { @class = "col-form-label control-label" })*@
                                    @Html.TextBoxFor(m => m.InteriorNumber, new { @class = "form-control input-text", @maxlength = "20", placeholder = HttpUtility.HtmlDecode(Html.DisplayNameFor(x => x.InteriorNumber).ToHtmlString()) })
                                </div>
                                <div class="col-12 col-md-4">
                                    @*@Html.LabelFor(m => m.ZipCode, new { @class = "col-form-label control-label" })*@
                                    @Html.TextBoxFor(m => m.ZipCode, new { @class = "form-control input-text", @maxlength = "5", placeholder = HttpUtility.HtmlDecode(Html.DisplayNameFor(x => x.ZipCode).ToHtmlString()) })
                                </div>
                                <div class="col-12 col-md-4">
                                    @Html.LabelFor(m => m.Colony, new { @class = "col-form-label control-label" })
                                    @Html.DropDownListFor(m => m.Colony, Model.ListColony, new { @class = "chosen-select" })
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-12 col-md-4">
                                    @Html.LabelFor(m => m.Municipality, new { @class = "col-form-label control-label" })
                                    @Html.DropDownListFor(m => m.Municipality, Model.ListMunicipality, new { @class = "chosen-select" })
                                </div>
                                <div class="col-12 col-md-4">
                                    @Html.LabelFor(m => m.State, new { @class = "col-form-label control-label" })
                                    @Html.DropDownListFor(m => m.State, Model.ListState, new { @class = "chosen-select" })
                                </div>
                                <div class="col-12 col-md-4">
                                    @Html.LabelFor(m => m.Country, new { @class = "col-form-label control-label" })
                                    @Html.DropDownListFor(m => m.Country, Model.ListCountry, new { @class = "chosen-select" })
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-12 col-md-8">
                                    <label class="col-form-label control-label">Domicilio Comercial</label>
                                    <div class="form-group">
                                        <div class="i-checks">
                                            <label style="font-weight:initial">
                                                <input id="DeliveryAddress" name="DeliveryAddress" type="checkbox" checked class="" value="true">
                                                Mismo que domicilio Fiscal
                                            </label>
                                        </div>
                                        @*<input id="DeliveryAddress" name="DeliveryAddress" type="checkbox" checked class="" value="true"> <label for="DeliveryAddress">Mismo que domicilio Fiscal</label>*@
                                        @*<input id="" name="DeliveryAddress" type="checkbox" class="" value="1" @(Model.MEMBRESIA_EDITAR.DESCUENTO_TEC == 1 ? "checked" : "")> <label for="descuentoTec">Exclusivo para Empleados Tec</label>*@
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Datos de Contacto</h5>
                    </div>
                    <div class="ibox-content">
                        <div class="form-horizontal">
                            <div class="form-group row">
                                <div class="col-12">
                                    <input type="hidden" name="indexPhone[]" id="indexPhone" />
                                    <input type="hidden" name="indexEmail[]" id="indexEmail" />
                                </div>
                                <div class="col-12 col-md-6 listContacts" id="ListEmails">
                                    <div class="row">
                                        <div class="col-12 col-md-10">
                                            @*<label class="col-form-label control-label">Email</label>*@
                                            <input type="hidden" name="Emails[0].TypeContact" value="@TypeContact.EMAIL.ToString()" />
                                            <input type="email" class="form-control input-text emails" maxlength="250" name="Emails[0].EmailOrPhone" placeholder="Email" />
                                        </div>
                                        <div class="col-12 col-md-2">
                                            @*<label class="col-form-label control-label heightLabel"></label>*@
                                            <button type="button" class="btn btn-button btn-add-email" value="email">+</button>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-12 col-md-6 listContacts" id="ListPhones">
                                    <div class="row">
                                        <div class="col-12 col-md-10">
                                            @*<label class="col-form-label control-label">Teléfono</label>*@
                                            <input type="hidden" name="Phones[0].TypeContact" value="@TypeContact.PHONE.ToString()" />
                                            <input type="text" class="form-control input-text phones" name="Phones[0].EmailOrPhone" placeholder="Teléfono" data-mask="9999-99-99-99" removeMaskOnSubmit="true" greedy="false" />
                                        </div>
                                        <div class="col-12 col-md-2">
                                            @*<label class="col-form-label control-label heightLabel">   </label>*@
                                            <button type="button" class="btn btn-button btn-add-phone" value="phone">+</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group row pull-right">
                                <div class="col-md-10 offset-2 text-right">
                                    <a href='@Url.Action("Index", "Provider")' class='btn btn-button'><i class="fa fa-times"></i> Cancelar</a>
                                    <button type="button" class="btn btn-button" onclick="validarDatos()"> <i class="fa fa-save"></i> Guardar </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        }

    </div>
</div>

@section Scripts {

    @Scripts.Render("~/plugins/validate")
    @Scripts.Render("~/plugins/toastr")
    <script src="~/Scripts/plugins/jasny/jasny-bootstrap.min.js"></script>
    <script src="~/Scripts/views/Provider/Create.js"></script>
    <script>
        var urlGetLocation = '@Url.Action("GetLocations")';
    </script>
}